export const types = {
  FETCH_ALL_MUTUAL_FUNDS: "FETCH_ALL_MUTUAL_FUNDS",
  FETCH_ALL_ETF: "FETCH_ALL_ETF",
  GET_ALL_MUTUAL_FUNDS: "GET_ALL_MUTUAL_FUNDS",
  GET_ALL_ETF: "GET_ALL_ETF",
  FETCHING_DATA: "FETCHING_DATA",
  DATA_FETCH_ERROR_MESSAGE: "DATA_FETCH_ERROR_MESSAGE",
};
